name: 'Gitter Notify'
description: 'Github notify - Github plugin'
inputs:
  room-id:
    description: 'Gitter room id in which message needs to be sent'
    required: true
  text:
    description: 'Message text that need to be displayed'
    required: true
  token:
    description: 'Gitter personal access token'
    required: true
  message-id:
    description: 'To replace existing message, Provide message id'
    required: false
outputs:
  message-id:
    description: 'Id of the submitted message'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'yellow'